-- Authors: Adam Henry, Shane Ludwig, Matthew O'Malley-Nichols

.headers on
.mode columns

-- Enables foreign key constraints
PRAGMA foreign_keys=ON;

DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS SALES_HISTORY;
DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS ITEM;
DROP TABLE IF EXISTS SKI;
DROP TABLE IF EXISTS BIKE;
DROP TABLE IF EXISTS SNOWBOARD;
DROP TABLE IF EXISTS MAINTAINS;
DROP TABLE IF EXISTS RENTS;

--EMPLOYEE: Step 1, Step 4, Step 8D
CREATE TABLE IF NOT EXISTS EMPLOYEE(
  eid  INT  NOT NULL PRIMARY KEY,
  salary DECIMAL(10,2),
  sid  INT,
  fname VARCHAR(20),
  lname VARCHAR(20),
  sFlag BOOLEAN NOT NULL DEFAULT FALSE,
  location VARCHAR(20),
  mflag BOOLEAN NOT NULL DEFAULT FALSE,
  skill CHAR,
  FOREIGN KEY (sid) REFERENCES EMPLOYEE(eid),
  FOREIGN KEY (location) REFERENCES INVENTORY(location)
);
-- SALES_HISTORY: Step 2, Step 4
CREATE TABLE IF NOT EXISTS SALES_HISTORY (
  date  TIMESTAMP  NOT NULL PRIMARY KEY,
  eid  INT  NOT NULL,
  iid  INT  NOT NULL,
  FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid),
  FOREIGN KEY (iid) REFERENCES ITEM(iid)
);
--INVENTORY: Step 1
CREATE TABLE IF NOT EXISTS INVENTORY (
  location  VARCHAR(20)  NOT NULL PRIMARY KEY
);
--CUSTOMER: Step 1
CREATE TABLE IF NOT EXISTS CUSTOMER(
  cid INT NOT NULL PRIMARY KEY,
  phone INT,
  email VARCHAR(64),
  fname VARCHAR(20),
  lname VARCHAR(20)
);
--ITEM: Step 1, Step 4
CREATE TABLE IF NOT EXISTS ITEM(
  iid INT NOT NULL PRIMARY KEY,
  type VARCHAR(20),
  price DECIMAL(8, 2),
  rating DECIMAL(8, 2),
  location VARCHAR(20) NOT NULL,
  eid INT NOT NULL,
  cid INT NOT NULL,
  FOREIGN KEY (location) REFERENCES INVENTORY(location),
  FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid),
  FOREIGN KEY (cid) REFERENCES CUSTOMER(cid)
);
--SKI: Step 8A
CREATE TABLE IF NOT EXISTS SKI(
  iid INT NOT NULL PRIMARY KEY,
  tip_width INT,
  waist_width int,
  length INT,
  FOREIGN KEY (iid) REFERENCES ITEM(iid)
);
--BIKE: Step 8A
CREATE TABLE IF NOT EXISTS BIKE(
  iid  INT  NOT NULL PRIMARY KEY,
  tire_size  DECIMAL(4, 2),
  front_suspension  VARCHAR(20),
  rear_suspension  VARCHAR(20),
  FOREIGN KEY (iid) REFERENCES ITEM(iid)
);
--SNOWBOARD: Step 8A
CREATE TABLE IF NOT EXISTS SNOWBOARD(
  iid INT NOT NULL PRIMARY KEY,
  length INT,
  camber VARCHAR(10),
  FOREIGN KEY (iid) REFERENCES ITEM(iid)
);
--MAINTAINS: Step 5
CREATE TABLE IF NOT EXISTS MAINTAINS(
  iid INT NOT NULL,
  eid INT NOT NULL,
  date TIMESTAMP,
  PRIMARY KEY (iid,eid),
  FOREIGN KEY (iid) REFERENCES ITEM(iid),
  FOREIGN KEY (eid) REFERENCES EMPLOYEE(eid)
);
--RENTS: Step 4
CREATE TABLE IF NOT EXISTS RENTS(
  cid INT NOT NULL,
  iid INT NOT NULL PRIMARY KEY,
  start_rental TIMESTAMP,
  end_rental TIMESTAMP,
  FOREIGN KEY (cid) REFERENCES CUSTOMER(cid),
  FOREIGN KEY (iid) REFERENCES ITEM(iid)
);
